
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://daf619e5-50c8-4d6e-ba5f-6c23df73b6ca.lovableproject.com"
additional_redirect_urls = ["https://daf619e5-50c8-4d6e-ba5f-6c23df73b6ca.lovableproject.com/verify", "https://daf619e5-50c8-4d6e-ba5f-6c23df73b6ca.lovableproject.com/login"]

[realtime]
enabled = true

[functions.process-refund]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

