
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuswvcremziknjbxwvsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1c3d2Y3JlbXppa25qYnh3dnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODQzMzcsImV4cCI6MjA1NjY2MDMzN30.dJqRG36Z10_eQvYJJdXjuHg7BSDQzsn7OZ6awFOzbg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
